algoritmo "ex20"
// Função :
// Autor : Matheus Souza Rodrigues (Gaviota)
// Data : 08/03/2024
// Seção de Declarações 
var
blusa, novelo:inteiro
resul:real
inicio
// Seção de Comandos
escreval("Digite o número de blusas que você fez: ")
leia(blusa)
escreval("Digite o número de novelos que você usou: ")
leia(novelo)
resul <- novelo / blusa
escreval("Você utiliza", resul," novelos para fazer cada blusa")

fimalgoritmo
