algoritmo "ex24"
// Função :
// Autor : Matheus Souza Rodrigues (Gaviota)
// Data : 13/03/2024
// Seção de Declarações 
var
agua, maracuja, refresco: real
inicio
// Seção de Comandos 
escreval("Digite quantos litros de refresco que você gostaria de fazer: ")
leia(refresco)
agua <- refresco * 0.8
maracuja <- refresco * 0.2
escreval("Será necessário", agua," litros de água e", maracuja," litros de suco")
escreval("de maracujá :)")
fimalgoritmo
