algoritmo "ex28"
// Função :
// Autor : Matheus Souza Rodrigues (Gaviota)
// Data : 05/03/2024
// Seção de Declarações
var
nota1, nota2, med: real
inicio
// Seção de Comandos

escreval("Escreva a primeira nota:")
leia(nota1)
escreval(" ")
escreval("Escreva a segunda nota:")
leia(nota2)
escreval(" ")
med <- ( (nota1 * 2) + (nota2 * 3) ) / 5
escreval("A média ponderada do aluno é ", med:4:2)
escreval(" ")
fimalgoritmo
