algoritmo "ex31"
// Função :
// Autor : Matheus Souza Rodrigues (Gaviota)
// Data : 12/03/2024
// Seção de Declarações 
var
peso, peso15, peso20:real
inicio
// Seção de Comandos 
escreval("Digite seu peso: ")
leia(peso)
peso15 <- peso * 1.15
peso20 <- peso * 0.8
escreval("O novo peso se você engordar 15% sobre o peso digitado:", peso15,"kg")
escreval("O novo peso se você emagrecer 20% sobre o peso digitado:", peso20,"kg")
fimalgoritmo
