algoritmo "ex33"
// Função :
// Autor : Matheus Souza Rodrigues (Gaviota)
// Data : 12/03/2024
// Seção de Declarações
var
altura, basema, baseme, trapezio:real
inicio
// Seção de Comandos 
escreval("Digite a altura do trapézio: ")
leia(altura)
escreval("Digite a base maior do trapézio: ")
leia(basema)
escreval("Digite a base menor do trapézio: ")
leia(baseme)
trapezio <- (basema + baseme) * altura / 2
escreval("A área do trapézio é", trapezio)
fimalgoritmo
