algoritmo "ex35"
// Função :
// Autor : Matheus Souza Rodrigues (Gaviota)
// Data : 12/03/2024
// Seção de Declarações
var
losango, diagonalma, diagonalme:real
inicio
// Seção de Comandos 
escreval("Digite a diagonal maior: ")
leia(diagonalma)
escreval("Digite a diagonal menor: ")
leia(diagonalme)
losango <- (diagonalma * diagonalme) / 2
escreval("A área do losango é:", losango)
fimalgoritmo
