algoritmo "ex01"
// Função :
// Autor : Matheus Souza Rodrigues
// Data : 02/04/2024
// Seção de Declarações 

var
num, resposta: inteiro

inicio
// Seção de Comandos
escreval("Digite um número")
escreva("Resposta: ")
leia(num)
escreval("")
res <- num mod 2
se (resposta = 1) entao
   escreval("O número digitado é impar.")
senao
   escreval("O número digitado é par.")
fimse
fimalgoritmo
